### ISSUE TITLE
No short URL generated

### ISSUE THREAD

**Issue by TMMC** [aloshbennett/shortly#17]
After clicking icon from urlbar or position from context menu the message is shown but it says that generated and copied short url is null (and in fact it is).

![shortly-bug](https://cloud.githubusercontent.com/assets/300390/8407966/3baec502-1e6c-11e5-8780-6119917d0e11.png)

**Comment by aloshbennett** [comment]
The bitly keys used by version 1.25 have hit their monthly usage limit. The version 1.60 uses a different set of keys and hence it should work. But that version is waiting to be reviewed:
https://addons.mozilla.org/en-us/firefox/addon/shortly-url-shortener/versions/?page=1#version-1.60

**Comment by TMMC** [comment]
The version 1.60 works fine, thanx :)
